
services:
  db:
    image: postgres:14
    container_name: task_management_db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5445:5432
#    volumes:
#      - ./data:/var/lib/postgresql/data